version: '3.4'

services:
    redbrowtest.api.web:
        depends_on:
            - db
        image: ${DOCKER_REGISTRY-}redbrowtestapiweb
        build:
            context: .
            dockerfile: RedBrowTest.API.Web/Dockerfile
        ports:
            - "6002:80"
        environment:
            - ConnectionStrings__RedBrowConnectionString=Server=db;Database=RedBrowTest;user id=${DATABASE_USER};password=${DATABASE_PASSWORD};TrustServerCertificate=True;
        
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        environment:
            SA_PASSWORD: "${DATABASE_PASSWORD}"
            ACCEPT_EULA: "Y"
        ports:
            - "${MSSQL_PORT}:1433"